GET http://localhost:8080/api/cars HTTP/1.1

###

POST http://localhost:8080/api/cars HTTP/1.1
Content-Type: application/json

{
  "color": "blue",
  "make": "Chevrolet",
  "model": "Volt",
  "year": 2020,
  "price": 50000
}

###

PUT http://localhost:8080/api/cars/3 HTTP/1.1
Content-Type: application/json

{
  "carId": 3,
  "color": "yellow",
  "make": "Chevrolet",
  "model": "Volt",
  "year": 2020,
  "price": 50000
}

###

GET http://localhost:8080/api/cars/3 HTTP/1.1