GET http://localhost:8080/api/categories
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkb2Rzd29ydGgiLCJkaXNwbGF5X25hbWUiOiJBbm5lIERvZHN3b3J0aCIsInVzZXJfa2luZCI6ImVtcGxveWVlIiwicm9sZXMiOlsidXNlciJdLCJpc19hY2Nlc3MiOnRydWUsImlzX3JlZnJlc2giOmZhbHNlLCJleHAiOjE2MTQ2MzI4NzB9.b4SH2monxNO79ERnsXQS19mxfXPdSNFFvQehmGnz5A0
